export const GET_USER_LOGGED_IN_DETAILS = "GET_USER_LOGGED_IN_DETAILS"

export const UPDATE_SHIPPING_DETAILS = "UPDATE_SHIPPING_DETAILS";
export const RESET_SHIPPING_STATE = "RESET_SHIPPING_DETAILS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const RESET_CART_STATE = "RESET_CART_STATE";